export const CAROUSEL = {
  ACTIVE_VIDEO_LIMIT: 10,
  PREFETCH_BEHIND: 2,
  CARD_WIDTH: 220,
  PREFETCH_MARGIN: "200px",
  INNER_SLIDE_WIDTH: 300,
  INNER_GAP: 20,
  INNER_NEIGHBOR_RANGE: 1,
  OUTER_SLIDES_PER_VIEW_MOBILE: 2.5,
} as const;